import "../styles/globals.css";
import ClientProviders from "../providers/ClientProviders";
import { ThemeRegistry } from "../providers/ThemeRegistry";
import LayoutWrapper from "@/components/layouts/LayoutWrapper";

export const metadata = {
  title: {
    default: "Dashboard | Invexis",
    template: "%s | Invexis",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`font-metropolis antialiased`}>
        <ClientProviders>
          <ThemeRegistry>
            <LayoutWrapper>{children}</LayoutWrapper>
          </ThemeRegistry>
        </ClientProviders>
      </body>
    </html>
  );
}
