import "../styles/globals.css";
import ClientProviders from "./ClientProviders";
import { Roboto } from "next/font/google";
import { JetBrains_Mono } from "next/font/google";
import { ThemeRegistry } from "./providers/ThemeRegistry";

// const roboto = Roboto({
//   subsets: ["latin"],
//   variable: "--font-roboto",
// });

// const sulphurPoint = Sulphur_Point({
//   subsets: ["latin"],
//   weight: ["300", "400", "700"],
//   variable: "--font-sulphur-point",
// });

const jetBrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-jetbrains-mono",
  weight: ["400", "500", "700"],
});

export const metadata = {
  title: {
    default: "Invexis | Dashboard",
    template: "Invexis | %s",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`font-metropolis antialiased`}>
        <ClientProviders>
          <ThemeRegistry>{children}</ThemeRegistry>
        </ClientProviders>
      </body>
    </html>
  );
}
